# Generated by Django 4.2.1 on 2023-05-06 13:36

import django.db.models.deletion
from django.db import migrations, models

import schedule.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("optout", models.BooleanField(verbose_name="Recording.Optout")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "acronym",
                    models.CharField(
                        max_length=50, validators=[schedule.utils.validate_acronym]
                    ),
                ),
                ("start", models.DateField()),
                ("duration_days", models.IntegerField(default=3)),
                (
                    "license",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="schedule.license",
                    ),
                ),
            ],
            options={
                "ordering": ["-start", "name"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("short", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("optout", models.BooleanField(verbose_name="Recording.Optout")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schedule.event"
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="`uuidgen`"
                    ),
                ),
            ],
            options={
                "ordering": ["event", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("duration_minutes", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("abstract", models.TextField(blank=True)),
                (
                    "optout",
                    models.BooleanField(verbose_name="This event will not be recorded"),
                ),
                ("persons", models.ManyToManyField(to="schedule.person")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.room",
                    ),
                ),
                ("slug", models.SlugField(default="foo")),
                (
                    "uuid",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="`uuidgen`"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="schedule.language",
                    ),
                ),
            ],
            options={
                "ordering": ["start"],
            },
        ),
    ]
