# Generated by Django 4.2.1 on 2023-05-06 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="duration_days",
            field=models.IntegerField(verbose_name="Duration (days)"),
        ),
        migrations.AlterField(
            model_name="event",
            name="license",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="schedule.license"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="short",
            field=models.CharField(max_length=10, verbose_name="short code"),
        ),
        migrations.AlterField(
            model_name="scheduleentry",
            name="duration_minutes",
            field=models.IntegerField(verbose_name="Duration (minutes)"),
        ),
        migrations.AlterField(
            model_name="scheduleentry",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="schedule.language"
            ),
        ),
        migrations.AlterField(
            model_name="scheduleentry",
            name="slug",
            field=models.SlugField(),
        ),
    ]
