# Generated by Django 4.2.1 on 2023-05-06 15:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_alter_event_duration_days_alter_event_license_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="optout",
        ),
        migrations.RemoveField(
            model_name="room",
            name="optout",
        ),
        migrations.RemoveField(
            model_name="scheduleentry",
            name="optout",
        ),
        migrations.AddField(
            model_name="room",
            name="has_recording",
            field=models.BooleanField(
                default=True, verbose_name="This room will be recorded and streamed"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheduleentry",
            name="do_record",
            field=models.BooleanField(
                default=True, verbose_name="This event will be recorded and streamed"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="room",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="scheduleentry",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
