# Generated by Django 4.2.1 on 2023-05-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_remove_person_optout_remove_room_optout_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="has_recording",
            field=models.BooleanField(
                default=True, verbose_name="This room will be recorded and streamed"
            ),
        ),
        migrations.AlterField(
            model_name="scheduleentry",
            name="do_record",
            field=models.BooleanField(
                default=True, verbose_name="This event will be recorded and streamed"
            ),
        ),
    ]
