# Generated by Django 4.2.1 on 2023-05-06 15:57

from django.db import migrations, models

import schedule.utils


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0004_alter_room_has_recording_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="acronym",
            field=models.CharField(
                max_length=50, unique=True, validators=[schedule.utils.validate_acronym]
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
